version: '3'
services:
  chain:
    build: ./ChainReaction
    networks:
      main:
  proxy:
    build: .
    ports:
      - 80:80
    depends_on:
      - chain
      - blog
    networks:
      main:
  blog:
    build: 
      context: ./MyBlog
      args:
        config: prod.yml
    networks:
      main:
networks:
  main:
    driver: bridge

